"""Short reference copy. Function signatures are read from src/value.rs."""

# name: (section, result, description)
BUILTINS = {
    "print": ("Values", ":null", 'Write one value as text, followed by `terminator`. Use `""` to omit the newline.'),
    "len": ("Values", "number", "Count list elements, dict entries, or Unicode characters in a string."),
    "has": ("Values", "boolean", "Test for a dict key or list index. Negative indices count from the end."),
    "get": ("Values", "value", "Read a dict key or list index, returning `fallback` when absent. Does not insert anything."),
    "push": ("Values", "number", "Append a copied value to a list; return its new length. The list argument must use `&`."),
    "return": ("Control", "[:return, …values]", "Construct a return request. Unconsumed, return its payload from the current function; an empty request returns `:null`."),
    "break": ("Control", ":break", "Construct a loop-stop request. Unconsumed, stop the nearest loop in this function; a parallel loop stops as a whole."),
    "continue": ("Control", ":continue", "Construct an iteration-stop request. Unconsumed, skip the rest of this iteration; a parallel iteration ends its trail."),
    "reject": ("Control", "[:reject, msg]", "Construct a rejection. Unconsumed in a function, try its next overload. Unhandled exhaustion reports all refusal messages and fails."),
    "exit": ("Control", "[:exit, code]", "Construct an exit request. Unconsumed, stop the program with an integer status from 0 through 255."),
    "panic": ("Control", "[:panic, msg]", "Construct a panic request. Unconsumed, stop the program with a rendered message, call trace, and status 1."),
    "alive": ("Concurrency", "boolean", "Whether the current trail is still live. Returns `:true` outside a trail."),
    "channel": ("Concurrency", "number", "The current trail’s zero-based index in its block. Requires a trail."),
    "send": ("Concurrency", "boolean", "Send to sibling trails; omit destinations for any sibling. Default `:wait` waits for receipt; `:detach` queues one message; `:broadcast` queues a copy per eligible sibling. False if none remain. Requires a trail."),
    "receive": ("Concurrency", "value, channel", "Wait for a sibling’s message and its sender index. Omit sources for any sibling. Returns `:null, :null` once none can send. Requires a trail."),
}

FS = {
    "join": ("Paths", "string", 'Join and normalize path components. `join("a", "/b")` yields `"a/b"`. Removes `.`; preserves `..`.'),
    "parent": ("Paths", "string", 'Parent directory; `"."` if the path has no directory component.'),
    "name": ("Paths", "string", "Final path component, including its extension."),
    "stem": ("Paths", "string", "Final component without its last extension."),
    "extension": ("Paths", "string", 'Last extension without its dot; `""` if absent.'),
    "absolute": ("Paths", "string", "Resolve against the working directory. Does not require existence or resolve symlinks."),
    "cwd": ("Locations", "string", "Current working directory."),
    "home": ("Locations", "string", "Current user’s home directory. Crashes if unavailable."),
    "temp": ("Locations", "string", "System temporary directory. Does not create a file or directory."),
    "exists": ("Inspect", "boolean", "Whether the path exists and can be inspected. Follows symlinks."),
    "is_file": ("Inspect", "boolean", "Whether the path is a regular file. False if absent or inaccessible."),
    "is_dir": ("Inspect", "boolean", "Whether the path is a directory. False if absent or inaccessible."),
    "size": ("Inspect", "bytes, reason", "Size from filesystem metadata, in bytes. Without a fallback, errors crash."),
    "modified": ("Inspect", "seconds, reason", "Modification time as Unix seconds, including fractions. Without a fallback, errors crash."),
    "read": ("Read", "string, reason", "Read the whole file as UTF-8. Without a fallback, read and encoding errors crash."),
    "lines": ("Read", "list, reason", "Read UTF-8 lines, without line endings. Without a fallback, errors crash."),
    "list": ("Read", "list, reason", "List matching entries as paths joined to `dir`. Sort within each directory; recurse depth-first when requested. Patterns support `*` and `?`. Without a fallback, errors crash."),
    "write": ("Write", "path, bytes", "Write text; return the path and UTF-8 byte count. `:replace` truncates, `:append` appends, `:new` requires a new file. Creates parent directories by default."),
    "copy": ("Write", "target", "Copy a file or directory tree. Overwrite and create parent directories by default. Other failures crash."),
    "move": ("Write", "target", "Rename a file or directory. Create parents by default; existing targets require `overwrite = :true`. Cross-filesystem moves may fail."),
    "remove": ("Write", "boolean", "Remove a file or empty directory; `recursive = :true` removes a directory tree. False if absent; other failures crash."),
    "make_dir": ("Write", "path", "Create a directory and, by default, its parents. An existing directory is fine; other failures crash."),
}

CONTROL_ROWS = [
    ("break()", ":break", "Nearest loop in this function", "Stop the loop; for a parallel loop, cancel its other iterations."),
    ("continue()", ":continue", "Nearest loop in this function", "End the current iteration."),
    ("return(values*)", "[:return, …values]", "Current function", "Return the payload; no payload means `:null`."),
    ("reject(msg)", "[:reject, msg]", "Function / overload resolution", "Try the next candidate. Unhandled exhaustion reports every refusal and fails."),
    ("exit(code)", "[:exit, code]", "Program", "Stop with status 0–255."),
    ("panic(msg)", "[:panic, msg]", "Program", "Stop with a diagnostic and status 1."),
]

ATOM_GROUPS = [
    ("values", "Values", [
        (":true", "Boolean true. Also returned by successful predicates."),
        (":false", "Boolean false; falsy."),
        (":null", "Absence or an empty result; falsy. Everything else is truthy, including 0 and empty collections."),
    ]),
    ("send-modes", "Send modes", [
        (":wait", "Wait until a sibling receives the message. Default for `send`."),
        (":detach", "Queue for one eligible sibling and continue immediately."),
        (":broadcast", "Queue one copy for each eligible sibling already spawned."),
    ]),
    ("write-modes", "Write modes", [
        (":replace", "Create or truncate a file. Default for `fs::write`."),
        (":append", "Append to a file; in cli, collect repeated argument values."),
        (":new", "Create a new file; fail if it already exists."),
    ]),
    ("fs-reasons", "Filesystem reasons", [
        (":not_found", "Path does not exist."),
        (":denied", "Permission denied."),
        (":exists", "Path already exists."),
        (":is_dir", "A file operation encountered a directory."),
        (":not_dir", "A directory operation encountered a non-directory."),
        (":encoding", "Invalid data, including non-UTF-8 text."),
        (":io", "Other I/O failure."),
    ]),
]

LANGUAGE = [
    ("bindings", "Bindings & values", "`:=` declares; `=` assigns; `_ = expression` explicitly discards a result. Lists and dicts copy by value. Use `&place` to pass a reference; mutations through it reach the caller.", 'name := "Hydra"\nuser := { :name : name, :ready : :true }\nprint user.name  // user[:name]\nitems := [1, 2]\npush &items, 3'),
    ("calls", "Calls", "Omit parentheses only for an outer statement or assignment RHS. Arguments use commas; nested calls require parentheses. A first argument starts on the callee’s line. Bare function names are values; zero-argument calls use `()`.", 'fn add(a, b)\n\treturn a + b\nend\n\ntotal := add 20, len([1, 2])\nprint total'),
    ("spacing", "Significant spacing", "`f -1` calls with a negative argument; `f - 1` subtracts. `f [1]` calls with a list; `f[1]` indexes. `f &x` passes a reference; `f & x` is bitwise AND. The formatter preserves these distinctions.", None),
    ("continuation", "Continuation", "A single newline continues an expression whenever syntax permits. A blank or whitespace-only line stops it. Comment-only lines are transparent. Precedence stays unchanged.", 'foo\n.bar\n.baz  // foo.bar.baz\n\n32\n-a    // 32 - a\n\n32\n\n-a    // two statements'),
    ("functions", "Functions & results", "Blocks close with `end`; indentation is cosmetic. Parameters can have defaults, require a reference (`&x`), or collect positional arguments (`xs*`). Parameters after `*` or `xs*` are named-only. `return` is an ordinary builtin; a bare `return` calls it with no arguments.", 'fn pair(x, offset = 1)\n\treturn x, x + offset\nend\n\na, b := pair 4\nf := pair  // keep the function itself'),
    ("handlers", "Control values", "A control builtin constructs an atom or tagged list. Binding, passing, or returning that value consumes it. An expression statement leaves it to a handler. Loop and return handlers stay within the current function; forward a request explicitly to let the caller handle it.", 'fn return_if(condition, value)\n\tif condition\n\t\treturn return(value)\n\tend\nend'),
    ("overloads", "Overloads & rejection", "Calls try candidates by signature; `:reject` or `[:reject, msg]` tries the next candidate. A successful fallback is silent. If all reject, an unconsumed rejection reports all messages and fails. Builtins can be shadowed; `::name` explicitly selects a global builtin.", None),
    ("modules", "Modules", "`use fs` imports a module; `fs::read(...)` selects a function. `use fs as files` renames it; `use fs as *` imports its names. Standard modules: `fs`, `env`, `text`, `json`, `io`, `time`, `http`, `list`, and `cli`.", 'use fs\ntext, reason := fs::read "optional.txt", ""\nif reason != :null\n\tprint "Using the default text"\nend'),
    ("loops", "Branches & loops", "Use `if` / `else if` / `else`, `for item in items`, or `while condition`. `break()` stops the nearest loop; `continue()` skips an iteration. Neither crosses a function boundary. There are no labeled breaks.", 'for n in [1, 2, 3]\n\tif n == 2\n\t\tcontinue()\n\tend\n\n\tprint n\nend'),
    ("trails", "Parallel trails", "Each `||` column is an independent trail; rows do not synchronize. `parallel` waits for all trails; `race` cancels losers after a winner finishes. `send` and `receive` communicate within the block. Parallel loops support the same loop-control atoms.", 'parallel\n\tsend "ready" || message := receive()\n\t             || print message\nend'),
    ("atoms", "Atoms & strings", "Atoms use `:name` or `:\"quoted name\"`. Bare names consume punctuation until whitespace, a delimiter (`()[]{},:\"`), or `//` / `||`. A dict keeps the colon between key and value. Strings are double-quoted; `\\(expression)` interpolates a value.", 'status := :some-other-prop+info\nrecord := { :status : status }\nprint "Status: \\(record.status)"'),
]

# module: (summary, function descriptions, short usage note, example)
MODULES = {
    "fs": ("Filesystem paths, inspection, reading, and writing.", FS,
        "Readers return value, reason. Without a fallback, operational failures crash.", None),
    "env": ("Script arguments, environment variables, and the host platform.", {
        "args": ("Environment", "list", "Arguments after `--`, excluding the script name. Embedding hosts supply these in VM options."),
        "get": ("Environment", "string, reason", "Read a variable. Missing names return `fallback, :not_found`; non-Unicode values return `fallback, :encoding`. Without a fallback, failures crash. Invalid names always crash."),
        "all": ("Environment", "dict", "Snapshot Unicode environment variables, sorted by name. Keys are atoms; variables with non-Unicode names or values are omitted."),
        "platform": ("Environment", "atom", "Host OS, such as `:macos`, `:linux`, or `:windows`."),
    }, "Run `hydra run script.hy -- arg1 arg2`. Interpreter options go before `--`. This module does not mutate the process environment.",
        'use env\nname := env::get "USER", "friend"\nprint "Hello, \\(name)"'),
    "text": ("Unicode string operations. Positions count characters, not bytes.", {
        "split": ("Strings", "list", "With `:null`, split on Unicode whitespace and discard empty fields. An explicit separator preserves empty fields; an empty separator splits into characters."),
        "join": ("Strings", "string", "Join a list of strings with the separator. An empty list produces an empty string."),
        "trim": ("Strings", "string", "Remove leading and trailing Unicode whitespace."),
        "replace": ("Strings", "string", "Replace every non-overlapping literal match. An empty `from` inserts at character boundaries, including both ends."),
        "find": ("Strings", "number or :null", "Zero-based character position of the first literal match; `:null` if absent. An empty needle matches at zero."),
        "starts_with": ("Strings", "boolean", "Whether text begins with the literal prefix."),
        "ends_with": ("Strings", "boolean", "Whether text ends with the literal suffix."),
        "lower": ("Strings", "string", "Unicode lowercase conversion, independent of locale."),
        "upper": ("Strings", "string", "Unicode uppercase conversion, independent of locale. May change character count."),
    }, "These functions require strings; they do not silently render other values.",
        'use text\nwords := text::split "  hello   Hydra  "\nprint text::join(words, " ")'),
    "json": ("Convert between JSON text and Hydra values.", {
        "parse": ("Conversion", "value, reason", "Objects become dicts with atom keys; arrays become lists; booleans and null become `:true`, `:false`, and `:null`. Invalid input gives `fallback, :invalid`, or crashes without a fallback."),
        "stringify": ("Conversion", "string", "Encode values, preserving dict order. Other atoms become JSON strings. `pretty = :true` indents. Functions, non-finite numbers, cycles, and excessive nesting crash."),
    }, "Numbers use Hydra’s floating-point representation: large JSON integers can lose precision. Object keys become atoms, but ordinary JSON string values stay strings.",
        'use json\nencoded := json::stringify { :name : "Hydra", :ready : :true }\nrecord := json::parse encoded\nprint record.name'),
    "io": ("UTF-8 standard input, output, and error streams.", {
        "read": ("Input", "string, reason", "Read stdin to EOF, preserving line endings. Empty input produces an empty string."),
        "read_line": ("Input", "string or :null, reason", "Read one line, removing its LF or CRLF ending. EOF produces `:null`; an empty line produces an empty string."),
        "lines": ("Input", "list, reason", "Read stdin to EOF as a list of lines, without line endings. This collects the entire input."),
        "write": ("Output", "bytes", "Render one value without a newline to `:stdout` or `:stderr`, flush, and return its UTF-8 byte count. Failures crash."),
        "flush": ("Output", ":null", "Flush `:stdout` or `:stderr`. Failures crash."),
        "is_terminal": ("Output", "boolean", "Whether `:stdin`, `:stdout`, or `:stderr` is connected to a terminal."),
    }, "Input supports `:stdin` only. Readers return value, reason; fallback overloads report `:encoding` or `:io`, while strict overloads crash. Read one line at a time for bounded memory. Concurrent readers share and serialize access to stdin.",
        'use io\nline := io::read_line()\nwhile line != :null\n\tprint line\n\tline = io::read_line()\nend'),
    "time": ("Clocks, sleeping, and timestamp conversion. All durations use seconds.", {
        "now": ("Clocks", "seconds", "Unix timestamp with fractional seconds. The system clock can jump."),
        "monotonic": ("Clocks", "seconds", "Elapsed seconds from the host process’s first call. Use differences to measure durations; unrelated to calendar time."),
        "sleep": ("Clocks", ":null", "Wait a finite, nonnegative number of seconds while other trails run. Scheduling can make the actual wait longer."),
        "parse": ("Dates", "seconds, reason", "Parse an RFC 3339 timestamp with an explicit offset or Z. Return Unix seconds; invalid input gives `fallback, :invalid`, or crashes without a fallback."),
        "format": ("Dates", "string", "Format Unix seconds in UTC using strftime directives such as `%Y-%m-%d %H:%M:%S`. Default `%+` produces RFC 3339. Invalid formats or dates crash."),
    }, "Use `now` for timestamps and `monotonic` for elapsed time. Negative timestamps represent dates before 1970.",
        'use time\nstart := time::monotonic()\ntime::sleep 0.01\nprint time::monotonic() - start'),
    "http": ("HTTP and HTTPS requests, text responses, and binary downloads.", {
        "request": ("Requests", "response, reason", "Send a method string or atom, with an optional UTF-8 body. Response fields are `.status`, `.headers`, `.body`, and final `.url`. HTTP error statuses remain ordinary responses."),
        "get": ("Requests", "response, reason", "GET shorthand for `request`. Response body must be UTF-8."),
        "post": ("Requests", "response, reason", "POST a UTF-8 string. Set content-type explicitly; use `json::stringify` for JSON payloads."),
        "head": ("Requests", "response, reason", "HEAD shorthand. Return status and headers with an empty `.body`, even when content-length describes a nonempty resource."),
        "put": ("Requests", "response, reason", "PUT a UTF-8 string. Set content-type explicitly; use `json::stringify` for JSON payloads."),
        "patch": ("Requests", "response, reason", "PATCH with a UTF-8 string. Set the content-type required by the server’s patch format."),
        "delete": ("Requests", "response, reason", "DELETE shorthand, with an optional named `body`."),
        "options": ("Requests", "response, reason", "OPTIONS shorthand, with an optional named `body`. Inspect response headers for supported operations."),
        "connect": ("Requests", "response, reason", "Send CONNECT using the URL’s authority as the request target. Return the handshake response and close the connection; tunnel streams are not exposed."),
        "trace": ("Requests", "response, reason", "TRACE shorthand. Return the server’s diagnostic response."),
        "download": ("Requests", "path, reason", "GET binary data to a file. Require a 2xx status, create parent directories, and replace the target only after the complete bounded download succeeds. Failure leaves an existing target intact."),
    }, "Method shorthands share `request` options and fallback behavior. Use `request` for custom methods. Headers are an atom-keyed dict of strings or lists of strings. Response header names are lowercase, with lists preserving repeated values. TLS certificates are verified; redirects are followed up to 10. `timeout` is a positive total duration in seconds; `max_bytes` caps the decoded body (16 MiB by default, buffered in memory). Each call has a strict and a fallback overload. Operational failures report a reason or crash; invalid arguments always crash.",
        'use http\nuse json\nbody := json::stringify { :ready : :true }\nresponse, reason := http::patch "https://example.com/item", body, :null,\n\theaders = { :content-type : "application/json" }\nif reason == :null\n\tprint response.status\nelse\n\tprint reason\nend'),

    "list": ("Eager list operations, with Rust-style callbacks and itertools conveniences.", {
        "range": ("Create", "list", "Exclusive integer range. One argument means 0 through start-1; negative steps count down. Step must be nonzero; integers must be exactly representable."),
        "repeat": ("Create", "list", "Copy value count times."),
        "map": ("Transform", "list", "Apply f(item) to each item."),
        "filter": ("Transform", "list", "Keep items whose f(item) is truthy."),
        "filter_map": ("Transform", "list", "Map and omit only :null; retain :false and zero."),
        "flat_map": ("Transform", "list", "Map each item to a list, then flatten one level."),
        "flatten": ("Transform", "list", "Concatenate one level of nested lists."),
        "enumerate": ("Transform", "list", "Produce [index, value] pairs, starting at zero."),
        "rev": ("Transform", "list", "Reverse item order."),
        "chain": ("Combine", "list", "Concatenate two lists."),
        "zip": ("Combine", "list", "Pair corresponding items; stop at the shorter list."),
        "unzip": ("Combine", "left, right", "Split a list of two-element pairs into two returned lists."),
        "interleave": ("Combine", "list", "Alternate left and right items, retaining the longer list’s remainder."),
        "cartesian_product": ("Combine", "list", "Every [left, right] pair, in left-major order."),
        "intersperse": ("Combine", "list", "Insert separator between adjacent items."),
        "take": ("Slice", "list", "Keep at most count leading items."),
        "skip": ("Slice", "list", "Omit at most count leading items."),
        "step_by": ("Slice", "list", "Keep every step-th item, starting with the first. Step must be positive."),
        "take_while": ("Slice", "list", "Keep the leading items satisfying f; stop at the first failure."),
        "skip_while": ("Slice", "list", "Skip the leading items satisfying f, then keep everything else."),
        "map_while": ("Slice", "list", "Map until f first returns :null; omit that result."),
        "chunks": ("Slice", "list", "Non-overlapping lists of positive size; include the final partial chunk."),
        "windows": ("Slice", "list", "Overlapping lists of positive size; include complete windows only."),
        "first": ("Search", "value or :null", "First item, or :null for an empty list."),
        "last": ("Search", "value or :null", "Last item, or :null for an empty list."),
        "nth": ("Search", "value or :null", "Item at a nonnegative zero-based index, or :null if absent."),
        "find": ("Search", "value or :null", "First item satisfying f, or :null."),
        "find_map": ("Search", "value or :null", "First non-null f(item), stopping immediately."),
        "position": ("Search", "index or :null", "First zero-based index satisfying f."),
        "rposition": ("Search", "index or :null", "Last zero-based index satisfying f; search backwards."),
        "any": ("Search", "boolean", "Whether any item satisfies f; short-circuit. False for an empty list."),
        "all": ("Search", "boolean", "Whether every item satisfies f; short-circuit. True for an empty list."),
        "count": ("Reduce", "number", "Number of items; equivalent to len(items)."),
        "fold": ("Reduce", "value", "Apply f(accumulator, item) from left to right, starting with initial."),
        "reduce": ("Reduce", "value or :null", "Fold using the first item as accumulator; :null for an empty list."),
        "sum": ("Reduce", "number", "Sum numeric items; zero for an empty list."),
        "product": ("Reduce", "number", "Multiply numeric items; one for an empty list."),
        "join": ("Reduce", "string", "Render items as text and join with separator."),
        "for_each": ("Effects", ":null", "Call f(item) in order, consuming and discarding each result."),
        "inspect": ("Effects", "list", "Call f(item) in order for side effects; return the original list."),
        "partition": ("Group", "matching, other", "Return two lists, preserving order, partitioned by f(item)."),
        "unique": ("Group", "list", "Keep the first occurrence of each deeply equal value."),
        "unique_by": ("Group", "list", "Keep the first item for each deeply equal f(item) key."),
        "dedup": ("Group", "list", "Remove consecutive duplicate values."),
        "dedup_by": ("Group", "list", "Remove an item when f(last_retained, item) is truthy."),
        "dedup_by_key": ("Group", "list", "Remove consecutive items with equal f(item) keys."),
        "counts": ("Group", "list", "Return [value, count] pairs in first-occurrence order."),
        "group_by": ("Group", "list", "Group all equal f(item) keys as [key, items] pairs, in first-key order."),
        "chunk_by": ("Group", "list", "Group consecutive equal f(item) keys as [key, items] pairs."),
        "sorted": ("Order", "list", "Stable ascending sort. Supports matching numbers, strings, atoms, or recursively ordered lists."),
        "sorted_by": ("Order", "list", "Stable sort using compare(a, b): negative, zero, or positive for less, equal, or greater."),
        "sorted_by_key": ("Order", "list", "Stable ascending sort by f(item), evaluated once per item."),
        "min": ("Order", "value or :null", "Smallest ordered item; first wins ties. Empty gives :null."),
        "max": ("Order", "value or :null", "Largest ordered item; last wins ties. Empty gives :null."),
        "min_by": ("Order", "value or :null", "Minimum by numeric comparator; first wins ties. Empty gives :null."),
        "max_by": ("Order", "value or :null", "Maximum by numeric comparator; last wins ties. Empty gives :null."),
        "min_by_key": ("Order", "value or :null", "Minimum by f(item), evaluated once per item; first wins ties. Empty gives :null."),
        "max_by_key": ("Order", "value or :null", "Maximum by f(item), evaluated once per item; last wins ties. Empty gives :null."),
        "combinations": ("Combinatorics", "list", "Size-item selections in input order, without replacement. Equal values at different positions remain distinct."),
        "permutations": ("Combinatorics", "list", "Size-item ordered selections without replacement, in input-index order."),
    }, "All operations are eager; no iter() or collect(). Inputs keep value semantics. Callbacks run in order, may capture variables or suspend, and their results are consumed as data. Predicates use normal truthiness. Ordering rejects mixed types, dicts, functions, and NaN; atoms sort by name. Counts and indices are nonnegative integers. Combinations/permutations of size zero give [[]]; size beyond length gives []. Expanding native operations cap output at one million elements; windows and combinatorial selections also count copied entries.",
        'use list\nvalues := list::range(10)\n    .list::map(fn(x) x * x)\n    .list::filter(fn(x) x > 20)\nprint values\nyes, no := list::partition(values, fn(x) x % 2 == 0)\nprint list::windows(yes, 2)'),
    "cli": ("Argument parsers with generated help, typed options, and subcommands.", {
        "parser": ("Build", "parser", "Create a copyable parser. prog defaults to the script filename; add_help registers -h and --help."),
        "add_argument": ("Build", ":null", "Add one positional name or option aliases through &parser. Return fields use atom keys; default dest strips leading dashes and changes hyphens to underscores."),
        "add_subparser": ("Build", ":null", "Attach a copy of a configured child parser. The chosen command name goes in dest; child fields merge into the result. Commands are required by default."),
        "parse_args": ("Parse", "dict, extras", "Parse explicit string arguments, or script arguments after -- when omitted. With strict = :true, reject unknown arguments and return [] as extras on success; strict = :false returns unknown arguments in extras. Print help/version to stdout and stop with status 0; print input errors to stderr and stop with status 2."),
        "format_help": ("Help", "string", "Render usage, description, arguments, choices, commands, and epilog without printing."),
        "format_usage": ("Help", "string", "Render the compact usage line without printing."),
    }, "Types: :string (default), :int (exact integers), :float (finite). Actions: :store, :store_true, :store_false, :store_const, :append, :append_const, :count, :help, :version. Use const for constant actions or an option with nargs=\"?\"; version supplies version text. nargs accepts a positive count, \"?\", \"*\", or \"+\". choices checks converted values. Absent values default to :null; flags to false/true, counts to 0, repeated values to []. String defaults are converted. Supports --name=value, -n3, -vv, negative numbers, and -- to end options. Long options require exact spelling. Parent options precede subcommands. Configure each child before attaching it; later edits do not alter the attached copy.",
        'use cli\np := cli::parser(description = "Greet someone")\ncli::add_argument(&p, "name", help = "Who to greet")\ncli::add_argument(&p, "-n", "--count", type = :int, default = 1)\nargs, extras := cli::parse_args(p, strict = :false)\nprint "Hello, \\(args.name)!"'),
}

ATOM_GROUPS += [
    ("streams", "Standard streams", [
        (":stdin", "Input stream for `io` readers and `is_terminal`."),
        (":stdout", "Default stream for `io::write`, `flush`, and `is_terminal`."),
        (":stderr", "Error output stream for `io::write`, `flush`, and `is_terminal`."),
    ]),
    ("module-reasons", "Additional module reasons", [
        (":invalid", "Malformed JSON or timestamp."),
        (":timeout", "HTTP operation exceeded its time limit."),
        (":dns", "HTTP hostname could not be resolved."),
        (":tls", "TLS negotiation or certificate verification failed."),
        (":network", "Other HTTP connection or protocol failure."),
        (":redirect", "HTTP redirect limit or redirect failure."),
        (":too_large", "HTTP response exceeded `max_bytes`."),
        (":http_status", "A download received a non-2xx response. Other HTTP functions return the response normally."),
    ]),
]


ATOM_GROUPS += [
    ("cli-options", "Command-line parsers", [
        (":string", "Parse a command-line value as text; default type."),
        (":int", "Parse a command-line value as an exactly representable integer."),
        (":float", "Parse a command-line value as a finite number."),
        (":store", "Store an argument value; default action."),
        (":store_true", "A present flag stores :true; absent defaults to :false."),
        (":store_false", "A present flag stores :false; absent defaults to :true."),
        (":store_const", "A present flag stores const."),
        (":append_const", "Each occurrence appends const to a list."),
        (":count", "Count occurrences of an option."),
        (":help", "Show parser help and exit successfully."),
        (":version", "Show the configured version text."),
    ]),
]
